reviewers:
  defaults:
    - muhsintiket
    - fahrinh
    - tafaquh-fiddin
    - davidasync19
    - rizqitiket
    - chriscassidy-tiket

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: true
